name: Flunk
description: Analyze you GitHub profile in a cyberpunk way
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  flutter_web_auth: ^0.2.4
  get: ^3.0.1
  dio: ^3.0.9
  shared_preferences: ^0.5.7+3
  flutter_icons: ^1.1.0
  clippy_flutter: ^1.1.1
  cached_network_image: ^2.2.0+1
  animated_text_kit: ^2.2.0
  percent_indicator: ^2.1.5
  fl_chart: ^0.10.0
  share: ^0.6.4+3
  screenshot: ^0.2.0
  animations: ^1.1.1
  image_picker: ^0.6.7+2
  image: ^2.1.13
  photo_view: ^0.9.2
  cloudinary_public: ^0.3.3
  permission_handler: ^5.0.1+1
  image_gallery_saver: ^1.5.0
  url_launcher: ^5.4.11
  intro_views_flutter: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Blanka
      fonts:
        - asset: assets/fonts/Blanka.otf
    - family: Riviera
      fonts:
        - asset: assets/fonts/Riviera.otf
    - family: Ultra
      fonts:
        - asset: assets/fonts/Ultra.otf
